=== kabit999/interoperability-now/trunk/tip/schema/TIPManifest-1-4.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Created:       2011-05-06 joerg     -->
<!-- Last edited:   2011-08-23 tingley   -->
<!-- Amendments:    2011-05-16 Attribute sectionname gots values starting with a lower case character -->
<!--                           Introducing attribute localizable for ObjectFile and removing the Localizable element -->
<!--                           Changing version attribute to 1.1 -->
<!--                2011-05-29 Additonal comment section ResponseComment added to OrderResponse -->
<!--                           ContributorTool added to OrderResponse                           -->
<!--                           Changing version attribute to 1.2 -->
<!--                2011-05-30 Eliminating BOM -->
<!--                2011-08-23 Updates for 1.3 -->
<!--                2011-11-03 Draft 1.4 -->
<!--                2011-03-02 Revised draft 1.4 -->
<!--                           Open-ended task system, replace hardcoded enums with URIs -->
<!--                           Add Name to to ObjectFile -->
<!--						   Remove @localize and @type attributes -->
<!--						   General streamlining and cleanup -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="en">
           XML Schema of the TIP Manifest. The Manifest specifies the entire content of an
           Interoperability Package.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="TIPManifest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GlobalDescriptor" type="GlobalDescriptor">
                    <xs:annotation xml:lang="en">
                        <xs:documentation xml:lang="en">The GlobalDescriptor identifies the package with a
                            unique UUID, and contains information on the creator of the package as well
                            as the order action associated with the package.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="PackageObjects" type="PackageObjects">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">PackageObjects contains all objects that are necessary
                            to fulfill the associated order action plus objects which might additionally support
                            this action.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:enumeration value="1.4" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="UniquePackageID" type="xs:anyURI">
        <xs:annotation>
            <xs:documentation xml:lang="en">The UniquePackageID is a URI that uniquely identifies
                this package.  The simplest way to satisfy this requirement is to assign the 
                package a UUID and express it as a URN, such as
                    urn:uuid:ace950d0-73d8-417d-a5c0-b70c2974f244
            </xs:documentation>
        </xs:annotation>
    </xs:simpleType>
    <xs:complexType name="GlobalDescriptor">
        <xs:sequence>
            <xs:element name="UniquePackageID" type="UniquePackageID" />
            <xs:element name="PackageCreator" type="PackageCreator" />
            <xs:choice>
            	<xs:element name="TaskRequest" type="TaskRequest" />
            	<xs:element name="TaskResponse" type="TaskResponse" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Task">
    	<xs:sequence>
    		<xs:element name="TaskType" type="xs:anyURI">
    			<xs:annotation>
    				<xs:documentation xml:lang="en">TODO: write me
    				</xs:documentation>
    			</xs:annotation>
    		</xs:element>
    		<xs:element name="SourceLanguage" type="xs:language">
    			<xs:annotation>
    				<xs:documentation xml:lang="en">TODO: write me
    				</xs:documentation>
    			</xs:annotation>
    		</xs:element>
    		<xs:element name="TargetLanguage" type="xs:language">
    			<xs:annotation>
    				<xs:documentation xml:lang="en">TODO: write me
    				</xs:documentation>
    			</xs:annotation>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>
    <xs:complexType name="TaskRequest">
    	<xs:sequence>
    		<xs:element name="Task" type="Task" />    	</xs:sequence>
    </xs:complexType>
    <xs:complexType name="InResponseTo">
      	<xs:sequence>
			<xs:element name="UniquePackageID" type="UniquePackageID" />
        	<xs:element name="PackageCreator" type="PackageCreator" />
  		</xs:sequence>
  	</xs:complexType>
	<xs:simpleType name="ResponseMessage">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Success" />
            <xs:enumeration value="Failure" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TaskResponse">
    	<xs:sequence>
	        <xs:element name="Task" type="Task" />
			<xs:element name="InResponseTo" type="InResponseTo" />
			<xs:element name="ResponseMessage" type="ResponseMessage" />
            <xs:element name="ResponseComment" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Provides additional 
                        information about the response, such as an error 
                        message, warnings, etc.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
   		</xs:sequence>
    </xs:complexType>
    <xs:complexType name="PackageCreator">
		<xs:annotation>
			<xs:documentation xml:lang="en">PackageCreator contains the credentials of the organization
		    				 that has generated the package and the tool that was used for the creation
		    				 operation as well as the intended communication type.
		    </xs:documentation>
		</xs:annotation>
		<xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="ID" type="xs:anyURI" />
            <xs:element name="Update" type="xs:dateTime" />
            <xs:element name="Tool" type="ContributorTool">
                <xs:annotation>
                    <xs:documentation xml:lang="en">ContributorTool identifies the tool that
                        created the package with name, identifier, and version.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ContributorTool">
        <xs:sequence>
            <xs:element name="ToolName" type="xs:string" />
            <xs:element name="ToolID" type="xs:anyURI" />
            <xs:element name="ToolVersion" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PackageObjects">
        <xs:annotation>
            <xs:documentation xml:lang="en">PackageObjectSet contains the accompanying resources that
                represent the neccessary objects to fulfill the task associated with the order action.
                These resources (PackageObjects) are organized in sections (PackageObjectSection) which
                are categorized by a specific section name through an obligatory attribute.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="PackageObjectSection" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ObjectFile" type="ObjectFile" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="type" type="xs:anyURI" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ObjectFile">
        <xs:annotation>
            <xs:documentation xml:lang="en">An ObjectFile is the actual resource that is employed by
                the task specified as order action. The resource's location within the package 
                (relative to the containing section) is identified by the value of the Location 
                element.  The package location may be normalized as mandated by the spec.  The 
                resource's original file path is contained in the optional Name element.  If
                Name is not present, it defaults to the value of Location.  There is also an
                optional Description element describing the file.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Location" type="xs:string" />
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="sequence">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== kabit999/interoperability-now/trunk/samples/peanut_butter/tip-response/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- TODO: correct the schema location to something like
     http://interoperability-now.org/schema/TIPP/TIPManifest-1-4.xsd -->
<TIPManifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="TIPManifest-1-4.xsd" version="1.4">
  <GlobalDescriptor>
    <UniquePackageID>urn:uuid:84983-zzz-0091-alpppq-184903b-aj1239</UniquePackageID>
    <!-- This is the information about the creator of this package -->
    <PackageCreator>
        <Name>Joe the Freelance Translator</Name>
        <ID>http://joestranslations.biz</ID>
        <Update>2011-05-18T19:03:15Z</Update>
        <Tool>
          <ToolName>Kilgray MemoQ Standard Edition</ToolName>
          <ToolID>http://www.kilgray.com</ToolID>
          <ToolVersion>6.0</ToolVersion>
        </Tool>
    </PackageCreator>
    <TaskResponse>
      <!-- The Response repeats what the task was -->
      <Task>
        <TaskType>http://interoperability-now.org/TIPP/schema/tasks/v1/translate</TaskType>
        <SourceLanguage>en-US</SourceLanguage>
        <TargetLanguage>fr-FR</TargetLanguage>
      </Task>
      <!-- Now describe the package we're responding to, using its
          - ID and creation information. -->
      <InResponseTo>
        <UniquePackageId>urn:uuid:12345-abc-6789-aslkjd-19193la-as9911</UniquePackageId>
        <PackageCreator>
          <Name>Welocalize</Name>
          <ID>http://w01.welocalize.com/globalsight</ID>
          <Update>2011-05-09T22:45:00Z</Update>
          <Tool>
            <ToolName>GlobalSight 9.0</ToolName>
            <ToolID>http://www.globalsight.com</ToolID>
           <ToolVersion>9.0</ToolVersion>
         </Tool>
        </PackageCreator>
      </InResponseTo>
      <!-- Now describe the results -->
      <ResponseMessage>Success</ResponseMessage>
      <!-- ResponseComment is intended to store supplemental 
         - (non-machine-readable) information, particularly in error cases.
         - In this case, the field is empty. -->
      <ResponseComment />
    </TaskResponse>
  </GlobalDescriptor>

  
  <!-- For the response TIPP, the STS and preview data is optional and 
     - has been omitted.  The only thing that the "translate" task requires
     - in a successful response is the XLIFF:doc file. -->
  <PackageObjects>

    <PackageObjectSection name="bilingual" 
      type="http://interoperability-now.org/TIPP/schema/tasks/v1/translate/bilingual">
      <ObjectFile sequence="1">
        <Name>Peanut_Buffer.xlf</Name>
        <Location>Peanut_Butter.xlf</Location>
      </ObjectFile>
    </PackageObjectSection>

  </PackageObjects>
</TIPManifest>
