=== kabit999/interoperability-now/branches/jtip1.5/tip/schema/TIPPManifest-1_5.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Created:       2011-05-06 joerg     -->
<!-- Last edited:   2011-08-23 tingley   -->
<!-- Amendments:    2011-05-16 Attribute sectionname gots values starting with a lower case character -->
<!--                           Introducing attribute localizable for ObjectFile and removing the Localizable element -->
<!--                           Changing version attribute to 1.1 -->
<!--                2011-05-29 Additonal comment section ResponseComment added to OrderResponse -->
<!--                           ContributorTool added to OrderResponse                           -->
<!--                           Changing version attribute to 1.2 -->
<!--                2011-05-30 Eliminating BOM -->
<!--                2011-08-23 Updates for 1.3 -->
<!--                2011-11-03 Draft 1.4 -->
<!--                2012-03-02 Revised draft 1.4 -->
<!--                           Open-ended task system, replace hardcoded enums with URIs -->
<!--                           Add Name to to ObjectFile -->
<!--						   Remove @localize and @type attributes -->
<!--						   General streamlining and cleanup -->
<!--                2012-07-22 Draft 1.5 -->
<!--                           For now, this is unchanged from 1.4 -->
<!--                2012-10-26 Revised Draft 1.5 -->
<!--                           Updated section type mechanism. -->
<!--                           Introduction of XML-DSIG and <Signature>. -->
<!--                           Revised ResponseMessage values. -->
<!--                2012-11-29 Further 1.5 draft revisions. -->
<!--                           Split off common descriptor to TIPPCommon.xsd -->
<xs:schema
        elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <xs:include schemaLocation="TIPPCommon-1_5.xsd" />
    <xs:annotation>
        <xs:documentation xml:lang="en">
           XML Schema of the TIPP Manifest. The Manifest specifies the entire content of an
           Interoperability Package.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="TIPPManifest">
        <xs:annotation>
            <xs:documentation xml:lang="en">Root element for a TIPP Request.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GlobalDescriptor" type="GlobalDescriptor"/>
                <xs:choice>
                    <xs:element name="TaskRequest" type="TaskRequest"/>
                    <xs:element name="TaskResponse" type="TaskResponse"/>
                </xs:choice>
                <xs:element name="Resources" type="Resources"/>
            </xs:sequence>
            <xs:attribute name="version" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:enumeration value="1.5" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
        
    <xs:complexType name="TaskRequest">
        <xs:complexContent>
            <xs:extension base="Task" />
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="Task">
        <xs:annotation>
            <xs:documentation xml:lang="en">Information to describe a task.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TaskType" type="xs:anyURI">
                <xs:annotation>
                    <xs:documentation xml:lang="en">URI that identifies the task type for this TIPP.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="SourceLanguage" type="xs:language">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Source language for this TIPP.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TargetLanguage" type="xs:language">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Target language for this TIPP.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TaskResponse">
         <xs:annotation>
            <xs:documentation xml:lang="en">Information to describe a task response.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="InResponseTo" type="InResponseTo" />
            <xs:element name="Response" type="Response" />
            <xs:element name="Comment" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Provides additional 
                        information about the response, such as an error 
                        message, warnings, etc.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="InResponseTo">
        <xs:annotation>
            <xs:documentation xml:lang="en">Information about the task to which a TIPP Response is
                responding, including identifying information about the specific TIPP Request.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Task">
               <xs:sequence>
                   <xs:element name="UniquePackageID" type="UniquePackageID" />
                   <xs:element name="Creator" type="Creator" />
               </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:simpleType name="Response">
         <xs:annotation>
            <xs:documentation xml:lang="en">An enumeration of accepted success and failure values for a 
                TIPP Response.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Success" />
            <xs:enumeration value="Invalid Manifest" />
            <xs:enumeration value="Invalid Payload" />
            <xs:enumeration value="Security Failure" />
            <xs:enumeration value="Unsupported Task Type" />
            <xs:enumeration value="Task Failure" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Resources">
        <xs:annotation>
            <xs:documentation xml:lang="en">Resources contains all resources that are necessary
              to fulfill the associated order action plus resources which might additionally support
              this action.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element ref="ResourceSection" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="ResourceSection" type="ResourceSectionType" abstract="true"/>
    
    <xs:complexType name="ResourceSectionType">
        <xs:annotation>
            <xs:documentation xml:lang="en">A collection of Resources.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element ref="FileResource" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:element name="Bilingual" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Input" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Output" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Preview" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="STS" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Tm" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Terminology" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Metrics" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Extras" type="ResourceSectionType" substitutionGroup="ResourceSection" />
    <xs:element name="Reference" type="ReferenceSectionType" substitutionGroup="ResourceSection" />
    <xs:complexType name="ReferenceSectionType">
        <xs:complexContent>
            <xs:restriction base="ResourceSectionType">
                <xs:sequence>
                    <xs:element ref="ReferenceFileResource" minOccurs="1" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="FileResource" type="FileResourceType" />
    
    <xs:complexType name="FileResourceType">
        <xs:annotation>
            <xs:documentation xml:lang="en">A FileResource is the actual resource that is employed by
                the task specified as order action. The resource's location within the package 
                (relative to the containing section) is identified by the value of the Location 
                element.  The package location may be normalized as mandated by the spec.  The 
                resource's original file path is contained in the optional Name element.  If
                Name is not present, it defaults to the value of Location.  There is also an
                optional Description element describing the file.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="Location" type="xs:string" />
            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="sequence">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:element name="ReferenceFileResource" type="ReferenceFileResourceType" />
    <xs:complexType name="ReferenceFileResourceType">
        <xs:annotation>
            <xs:documentation xml:lang="en">A specialized FileResource for reference 
                documents.  This adds the optional languageChoice attribute to indicate
                whether the resource is related to the source language, target language,
                or both.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="FileResourceType">
                <xs:attribute name="languageChoice" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Source" />
                            <xs:enumeration value="Target" />
                            <xs:enumeration value="Bilingual" />
                            <xs:enumeration value="Multilingual" />
                            <xs:enumeration value="Other" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== kabit999/interoperability-now/branches/jtip1.5/tip/jtip/src/test/resources/com/globalsight/tip/data/reference-request.xml
<?xml version="1.0" encoding="UTF-8"?>
<TIPPManifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    xsi:noNamespaceSchemaLocation="http://schema.interoperability-now.org/tipp/TIPPManifest-1_5.xsd" 
    version="1.5">
  <GlobalDescriptor>
    <UniquePackageID>urn:uuid:12345-abc-6789-aslkjd-19193la-as9911</UniquePackageID>
    <Creator>
      <Name>Test Company</Name>
      <ID>http://127.0.0.1/test</ID>
      <Date>2011-05-09T22:45:00Z</Date>
      <Tool>
        <ToolName>TestTool</ToolName>
        <ToolID>http://interoperability-now.org/</ToolID>
        <ToolVersion>1.0</ToolVersion>
      </Tool>
    </Creator>
    <!-- No dsig in this file, for simplicity -->
  </GlobalDescriptor>
  <TaskRequest>
    <TaskType>http://schema.interoperability-now.org/tipp/v1.5/tasks/translate-strict-bitext</TaskType>
    <SourceLanguage>en-US</SourceLanguage>
    <TargetLanguage>fr-FR</TargetLanguage>
  </TaskRequest>
  <Resources>
    <Bilingual name="bilingual">
      <FileResource sequence="1">
        <Name>Peanut_Butter.xlf</Name>
        <Location>Peanut_Butter.xlf</Location>
      </FileResource>
    </Bilingual>
    <Reference name="reference">
      <ReferenceFileResource sequence="1" languageChoice="Source">
        <Location>Sample.pdf</Location>
        <Description>Source Language PDF</Description>
      </ReferenceFileResource>
      <ReferenceFileResource sequence="2" languageChoice="Bilingual">
        <Location>PreviousTranslation.xlf</Location>
        <Description>Previous translation (XLIFF:doc format)</Description>
      </ReferenceFileResource>
      <ReferenceFileResource sequence="3">
        <Location>Style.pdf</Location>
        <Description>Style guide.</Description>
      </ReferenceFileResource>
    </Reference>
    <Preview name="preview">
      <FileResource sequence="1">
        <Location>Peanut_Butter.html.skl</Location>
      </FileResource>
      <FileResource sequence="2">
        <Location>resources/20px-Padlock-silver.svg.png</Location>
      </FileResource>
      <FileResource sequence="3">
        <Location>resources/load.php</Location>
      </FileResource>
      <FileResource sequence="4">
        <Location>resources/290px-PeanutButter.jpg</Location>
      </FileResource>
      <FileResource sequence="5">
        <Location>resources/load(1).php</Location>
      </FileResource>
      <FileResource sequence="6">
        <Location>resources/magnify-clip.png</Location>
      </FileResource>
    </Preview>
  </Resources>
</TIPPManifest>
